#pragma once

// Minimal clean-room FTD2XX compatibility declarations used by this emulator.
// This header intentionally contains only the ABI surface required by
// src/ftd2xx_emu.cpp and does not redistribute the vendor SDK header.

#include <windows.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef PVOID FT_HANDLE;
typedef ULONG FT_STATUS;

enum {
    FT_OK = 0,
    FT_INVALID_HANDLE = 1,
    FT_DEVICE_NOT_FOUND = 2,
    FT_DEVICE_NOT_OPENED = 3,
    FT_IO_ERROR = 4,
    FT_INSUFFICIENT_RESOURCES = 5,
    FT_INVALID_PARAMETER = 6,
};

enum {
    FT_OPEN_BY_SERIAL_NUMBER = 1,
    FT_OPEN_BY_DESCRIPTION = 2,
};

#define FT_LIST_NUMBER_ONLY 0x80000000UL
#define FT_LIST_BY_INDEX    0x40000000UL
#define FT_FLAGS_OPENED     0x00000001UL
#define FT_EVENT_RXCHAR     0x00000001UL
#define FT_PURGE_RX         0x00000001UL
#define FT_PURGE_TX         0x00000002UL

// FT_DEVICE enum value used by the emulated dongle.
#define FT_DEVICE_232R 5UL

typedef struct _ft_device_list_info_node {
    ULONG Flags;
    ULONG Type;
    ULONG ID;
    DWORD LocId;
    char SerialNumber[16];
    char Description[64];
    FT_HANDLE ftHandle;
} FT_DEVICE_LIST_INFO_NODE, *PFT_DEVICE_LIST_INFO_NODE;

#if defined(_WIN32)
#  define RNET_FTD2XX_EXPORT __declspec(dllexport)
#else
#  define RNET_FTD2XX_EXPORT
#endif

RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_Open(int, FT_HANDLE*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_ListDevices(PVOID, PVOID, DWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_CreateDeviceInfoList(LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetDeviceInfoList(FT_DEVICE_LIST_INFO_NODE*, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_OpenEx(PVOID, DWORD, FT_HANDLE*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_Close(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_Read(FT_HANDLE, LPVOID, DWORD, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_Write(FT_HANDLE, LPVOID, DWORD, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetQueueStatus(FT_HANDLE, DWORD*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetStatus(FT_HANDLE, DWORD*, DWORD*, DWORD*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetEventStatus(FT_HANDLE, DWORD*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetBreakOn(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetBreakOff(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetWaitMask(FT_HANDLE, DWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_WaitOnMask(FT_HANDLE, DWORD*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetDivisor(FT_HANDLE, USHORT);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetEventNotification(FT_HANDLE, DWORD, PVOID);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_IoCtl(FT_HANDLE, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetBaudRate(FT_HANDLE, ULONG);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetDataCharacteristics(FT_HANDLE, UCHAR, UCHAR, UCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetFlowControl(FT_HANDLE, USHORT, UCHAR, UCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_ResetDevice(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_ResetPort(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_CyclePort(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_StopInTask(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_RestartInTask(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetDtr(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_ClrDtr(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetRts(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_ClrRts(FT_HANDLE);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetModemStatus(FT_HANDLE, ULONG*);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetChars(FT_HANDLE, UCHAR, UCHAR, UCHAR, UCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_Purge(FT_HANDLE, ULONG);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetTimeouts(FT_HANDLE, ULONG, ULONG);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetLatencyTimer(FT_HANDLE, UCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetLatencyTimer(FT_HANDLE, PUCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetBitMode(FT_HANDLE, UCHAR, UCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetBitMode(FT_HANDLE, PUCHAR);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_SetUSBParameters(FT_HANDLE, ULONG, ULONG);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_EE_UASize(FT_HANDLE, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_EE_UARead(FT_HANDLE, PUCHAR, DWORD, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_EE_UAWrite(FT_HANDLE, PUCHAR, DWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetDriverVersion(FT_HANDLE, LPDWORD);
RNET_FTD2XX_EXPORT FT_STATUS WINAPI FT_GetLibraryVersion(LPDWORD);

#ifdef __cplusplus
}
#endif
